#!/usr/bin/env python3
"""
reconcile-assets.py — write back what the build actually chose.

WHY: ASSET-PLAN.md leaves forks open on purpose ("office-collaboration.mp4 OR
phase2-augmentation-happy-meeting.mp4 — pick ONE"). The build resolves them and the decision
dies at the bench, so the next video re-opens the same fork and the plan slowly stops describing
the thing that shipped. Same failure class as beat-map drift, one level up.

  usage: reconcile-assets.py <project-dir> [--write]

Reports, per scene: assets referenced by index.html, assets present but UNUSED, assets referenced
but MISSING, and any unresolved fork in ASSET-PLAN.md with the choice the build made.
--write appends a RESOLVED section to ASSET-PLAN.md.
"""
import re, sys, os, json
from pathlib import Path

FORK_RE = re.compile(r'^(?P<line>.*?\b(?:OR|or)\b.*?(?:pick ONE|pick one|—\s*pick).*)$', re.M)

def scene_dirs(project):
    base = Path(project) / "hyperframes-v3" / "scenes"
    return sorted([d for d in base.iterdir() if (d / "index.html").exists()]) if base.exists() else []

def referenced(scene):
    html = (scene / "index.html").read_text(encoding="utf-8", errors="ignore")
    return {os.path.basename(m) for m in re.findall(r'assets/([A-Za-z0-9._\-]+)', html)}

def main():
    if len(sys.argv) < 2: sys.exit(__doc__)
    project = Path(sys.argv[1]); write = "--write" in sys.argv
    scenes = scene_dirs(project)
    if not scenes: sys.exit(f"no scenes under {project}/hyperframes-v3/scenes")

    lines, total_unused = [], 0
    for sc in scenes:
        used = referenced(sc)
        adir = sc / "assets"
        present = {p.name for p in adir.iterdir() if p.is_file()} if adir.exists() else set()
        present = {p for p in present if not p.endswith((".bak", ".json"))}
        unused = sorted(present - used)
        missing = sorted(u for u in used if u not in present and not u.endswith(".json"))
        total_unused += len(unused)
        print(f"{sc.name}: {len(used)} referenced, {len(unused)} unused, {len(missing)} missing")
        for u in unused:  print(f"    unused   {u}")
        for m in missing: print(f"    \033[31mMISSING  {m}\033[0m")
        if used:
            lines.append(f"- **{sc.name}** — used: " + ", ".join(f"`{u}`" for u in sorted(used)))

    plan = project / "ASSET-PLAN.md"
    if plan.exists():
        txt = plan.read_text(encoding="utf-8", errors="ignore")
        forks = [m.group("line").strip() for m in FORK_RE.finditer(txt)]
        if forks:
            print(f"\nunresolved forks in ASSET-PLAN.md: {len(forks)}")
            for f in forks: print(f"    {f[:130]}")
        if write:
            block = ("\n\n---\n\n## RESOLVED BY THE BUILD (generated by tools/reconcile-assets.py)\n\n"
                     "What each scene actually references. Generated after the build — the plan above states\n"
                     "intent, this states outcome. Do not hand-edit; re-run the tool.\n\n" + "\n".join(lines) + "\n")
            txt = re.sub(r'\n\n---\n\n## RESOLVED BY THE BUILD.*$', '', txt, flags=re.S)
            plan.write_text(txt.rstrip() + block, encoding="utf-8")
            print(f"\nwrote RESOLVED section to {plan}")
    print(f"\ntotal unused assets across scenes: {total_unused}")

if __name__ == "__main__":
    main()
