#!/usr/bin/env python3
"""
send-email.py - Send AI news digest via email

Usage:
    python3 send-email.py <digest-file.md>

Environment variables required:
    EMAIL_SMTP_SERVER - SMTP server hostname
    EMAIL_SMTP_PORT - SMTP server port
    EMAIL_FROM - Sender email address
    EMAIL_PASSWORD - Email password or app password
    EMAIL_TO - Recipient email address
    EMAIL_SUBJECT_PREFIX - Subject line prefix
"""

import os
import sys
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables from JARVIS .env file
jarvis_env = Path.home() / "Library" / "CloudStorage" / "Dropbox" / "jarvis" / ".env"
if jarvis_env.exists():
    load_dotenv(jarvis_env)


def read_digest(file_path: str) -> tuple[str, str, int]:
    """Read digest file and extract title, content, and article count."""
    with open(file_path, 'r') as f:
        content = f.read()

    # Extract article count from "New articles today: N" (v2) or "Articles: N" (v1)
    import re
    article_count = 0
    m = re.search(r'New articles today:\*?\*?\s*(\d+)', content)
    if not m:
        m = re.search(r'^Articles:\s*(\d+)', content, re.MULTILINE)
    if m:
        try:
            article_count = int(m.group(1))
        except (IndexError, ValueError):
            pass

    # Extract title (first line starting with #)
    title = "AI News Digest"
    for line in content.split('\n'):
        if line.startswith('# '):
            title = line[2:].strip()
            break

    return title, content, article_count


def create_html_email(title: str, content: str, article_count: int) -> str:
    """Convert markdown digest to HTML email."""
    # Simple markdown to HTML conversion
    html = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }}
            h1 {{
                color: #2c3e50;
                border-bottom: 3px solid #3498db;
                padding-bottom: 10px;
            }}
            h2 {{
                color: #34495e;
                margin-top: 30px;
            }}
            h3 {{
                color: #555;
                margin-top: 20px;
            }}
            a {{
                color: #3498db;
                text-decoration: none;
            }}
            a:hover {{
                text-decoration: underline;
            }}
            .stats {{
                background: #ecf0f1;
                padding: 15px;
                border-radius: 5px;
                margin: 20px 0;
            }}
            .article {{
                border-left: 3px solid #3498db;
                padding-left: 15px;
                margin: 20px 0;
            }}
            .footer {{
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #ddd;
                color: #777;
                font-size: 0.9em;
            }}
        </style>
    </head>
    <body>
    """

    # Convert markdown to HTML (simple conversion)
    lines = content.split('\n')
    in_article = False

    for line in lines:
        line = line.strip()

        if not line:
            continue
        elif line.startswith('# '):
            html += f"<h1>{line[2:]}</h1>\n"
        elif line.startswith('## '):
            if '📊 Statistics' in line or '📰 Top Stories' in line:
                html += f"<h2>{line[3:]}</h2>\n"
            else:
                html += f"<h2>{line[3:]}</h2>\n"
        elif line.startswith('### '):
            if in_article:
                html += "</div>\n"
            html += f'<div class="article"><h3>{line[4:]}</h3>\n'
            in_article = True
        elif line.startswith('**'):
            # Bold text like "Source: X | Topics: Y"
            html += f"<p><strong>{line.replace('**', '')}</strong></p>\n"
        elif line.startswith('[Read more'):
            # Extract URL from markdown link
            url = line.split('(')[1].split(')')[0] if '(' in line else '#'
            html += f'<p><a href="{url}">Read full article →</a></p>\n'
        elif line.startswith('- '):
            # List items
            html += f"<li>{line[2:]}</li>\n"
        elif line == '---':
            # Horizontal rule (skip in email)
            continue
        elif line.startswith('*Generated by'):
            # Footer
            html += f'<div class="footer">{line}</div>\n'
        else:
            # Regular paragraph
            html += f"<p>{line}</p>\n"

    if in_article:
        html += "</div>\n"

    html += """
    </body>
    </html>
    """

    return html


def send_email(digest_file: str):
    """Send digest via email."""
    # Check for required environment variables
    required_vars = [
        'EMAIL_SMTP_SERVER', 'EMAIL_SMTP_PORT',
        'EMAIL_FROM', 'EMAIL_PASSWORD', 'EMAIL_TO'
    ]

    missing_vars = [var for var in required_vars if not os.getenv(var)]
    if missing_vars:
        print(f"Error: Missing environment variables: {', '.join(missing_vars)}")
        print("Please configure email settings in email-config.sh")
        return 1

    # Read configuration
    smtp_server = os.getenv('EMAIL_SMTP_SERVER')
    smtp_port = int(os.getenv('EMAIL_SMTP_PORT'))
    from_email = os.getenv('EMAIL_FROM')
    password = os.getenv('EMAIL_PASSWORD')
    to_email = os.getenv('EMAIL_TO')
    subject_prefix = os.getenv('EMAIL_SUBJECT_PREFIX', 'JARVIS AI News Digest')

    # Read digest
    try:
        title, content, article_count = read_digest(digest_file)
    except Exception as e:
        print(f"Error reading digest: {e}")
        return 1

    # Create email
    date_str = datetime.now().strftime('%Y-%m-%d')
    subject = f"{subject_prefix} - {date_str} ({article_count} articles)"

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = from_email
    msg['To'] = to_email

    # Plain text version (fallback)
    text_part = MIMEText(content, 'plain')
    msg.attach(text_part)

    # HTML version
    html_content = create_html_email(title, content, article_count)
    html_part = MIMEText(html_content, 'html')
    msg.attach(html_part)

    # Send email
    try:
        print(f"Connecting to {smtp_server}:{smtp_port}...")
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()

        print(f"Logging in as {from_email}...")
        # Remove spaces from password (in case copied with spaces from Google)
        password_clean = password.replace(' ', '')
        server.login(from_email, password_clean)

        print(f"Sending email to {to_email}...")
        server.send_message(msg)
        server.quit()

        print(f"✓ Email sent successfully: {subject}")
        return 0

    except smtplib.SMTPAuthenticationError:
        print("✗ Email authentication failed. Check your password/app password.")
        return 1
    except Exception as e:
        print(f"✗ Email sending failed: {e}")
        return 1


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python3 send-email.py <digest-file.md>")
        sys.exit(1)

    digest_file = sys.argv[1]
    if not Path(digest_file).exists():
        print(f"Error: File not found: {digest_file}")
        sys.exit(1)

    exit_code = send_email(digest_file)
    sys.exit(exit_code)
